# Generated by Django 5.1.3 on 2024-11-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaultUser.png', null=True, upload_to=''),
        ),
    ]
