# Generated by Django 5.1.3 on 2024-11-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
