# Generated by Django 5.1.3 on 2024-11-25 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1-123-456-7890'.", regex='^\\+?1?\\-?\\d{3}\\-\\d{3}-\\d{4}$')]),
        ),
    ]
