# Generated by Django 5.1.1 on 2024-11-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
