# Generated by Django 5.1.3 on 2025-01-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_userjsondata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjsondata',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
